Controllers/HobbyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Portfolio_Site.Data;
using Portfolio_Site.Models;

namespace Portfolio_Site.Controllers
{
    public class HobbyController : Controller
    {
        private readonly _Portfolio_Site_Dbcontext _context;

        public HobbyController(_Portfolio_Site_Dbcontext context)
        {
            _context = context;
        }

        // GET: Hobby
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hobbys.ToListAsync());
        }

        // GET: Hobby/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hobby = await _context.Hobbys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hobby == null)
            {
                return NotFound();
            }

            return View(hobby);
        }

        // GET: Hobby/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Hobby/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("Naam")] Hobby hobby)
        {
            if (ModelState.IsValid)
            {
                Port_Eigenaar eigenaar = await _context.Port_Eigenaar.FindAsync(id);
                hobby.port_Eigenaar = eigenaar;
                _context.Add(hobby);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hobby);
        }

        // GET: Hobby/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hobby = await _context.Hobbys.FindAsync(id);
            if (hobby == null)
            {
                return NotFound();
            }
            return View(hobby);
        }

        // POST: Hobby/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naam")] Hobby hobby)
        {
            if (id != hobby.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hobby);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HobbyExists(hobby.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hobby);
        }

        // GET: Hobby/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hobby = await _context.Hobbys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hobby == null)
            {
                return NotFound();
            }

            return View(hobby);
        }

        // POST: Hobby/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hobby = await _context.Hobbys.FindAsync(id);
            _context.Hobbys.Remove(hobby);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HobbyExists(int id)
        {
            return _context.Hobbys.Any(e => e.Id == id);
        }
    }
}

Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Portfolio_Site.Data;
using Portfolio_Site.Models;
using Microsoft.AspNetCore.Identity;
using Portfolio_Site.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Portfolio_Site.Models.ViewModels;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace Portfolio_Site.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly _Portfolio_Site_Dbcontext _context;
        private readonly UserManager<_Portfolio_Site_User> _userManager;
        private readonly IWebHostEnvironment _hostEnvironment;
        //private readonly IActionContextAccessor _accessor;

        public ProjectController(_Portfolio_Site_Dbcontext context, UserManager<_Portfolio_Site_User> userManager, IWebHostEnvironment hostEnvironment/*, IActionContextAccessor accessor*/)
        {
            _context = context;
            _userManager = userManager;
            _hostEnvironment = hostEnvironment;
            //_accessor = accessor;
        }

        // GET: Projects
        [Authorize(Roles = "Moderator")]
        public async Task<IActionResult> Index()
        {
            var wDPR_BuurtApp_3GContext = _context.Projects.Include(m => m.Categorie).Include(m => m.User);
            return View(await wDPR_BuurtApp_3GContext.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id, String sorteerVolgorde, string sorteerType)
        {
            if (sorteerType == null)
            {
                sorteerType = "Votes";
            }
            if (sorteerVolgorde == null)
            {
                sorteerVolgorde = "aflopend";
            }
            var user = await _userManager.FindByIdAsync(this.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            //Check of ingelogd user moderator is. Boolean wordt meegestuurd in de viewdata
            ViewData["UserIsModerator"] = false;
            if (await _userManager.IsInRoleAsync(user, "Moderator"))
            {
                ViewData["UserIsModerator"] = true;
            }
            ViewData["sorteerVolgorde"] = sorteerVolgorde;
            ViewData["sorteerType"] = sorteerType;

            ViewData["LoggedInID"] = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if (id == null)
            {
                return NotFound();
            }

            var Project = await _context.Projects
                .Include(m => m.User)
                .Include(x=>x.Categorie)
                .FirstOrDefaultAsync(m => m.MeldingID == id);
            if (Project == null)
            {
                return NotFound();
            }

            Project.AantalViews += 1;
            _context.Update(Project);
            await _context.SaveChangesAsync();

            MaakProjectVM reactieVM = new MaakProjectVM();
            return View(Project);
        }
        
        // GET: Projects/Create
        public IActionResult Create()
        {
            ViewData["LoggedInID"] = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewData["CategorieID"] = new SelectList(_context.Categorie, "CategorieID", "CategorieID");
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id");
            List<Categorie> categorieLijst = _context.Categorie.ToList();
            ViewBag.categorieLijst = categorieLijst;
            return View();
        }
        
        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProjectID,UserID,Titel,Omschrijving,CategorieID,ImageFile,Datum,Gesloten")] Project ervaring)
        {
            if(_context.Projects.Where(m => m.Titel.Contains(ervaring.Titel)).Any())
            {
               ModelState.AddModelError("Titel", "Titel lijkt te erg op een bestaande titel.");
            }
            if (ModelState.IsValid)
            {
                //Afbeelding van de Project wordt een generieke "geen afbeelding" indien de gebruiker geen foto upload
                if (ervaring.ImageFile == null)
                {
                    ervaring.ImageName = "geenafbeelding211259326.png";
                }
                else
                {
                    //Verander de filenaam voor het model naar de bestandsnaam + de extensie. De foto wordt opgeslagen in de wwwroot folder.
                    string wwwrootPath = _hostEnvironment.WebRootPath;
                    string FileName = Path.GetFileNameWithoutExtension(ervaring.ImageFile.FileName);
                    string extension = Path.GetExtension(ervaring.ImageFile.FileName);
                    ervaring.ImageName = FileName = FileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = Path.Combine(wwwrootPath + "/Images/" + FileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await ervaring.ImageFile.CopyToAsync(fileStream);
                    }
                }

                _context.Add(ervaring);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(OverzichtProjecten));
            }
            ViewData["CategorieID"] = new SelectList(_context.Categorie, "CategorieID", "CategorieID", ervaring.CategorieID);
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", ervaring.UserID);
            ViewData["LoggedInID"] = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            List<Categorie> categorieLijst = _context.Categorie.ToList();
            ViewBag.categorieLijst = categorieLijst;
            return View();
        }
        [Authorize(Roles = "Moderator")]
        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Project = await _context.Projects.FindAsync(id);
            if (Project == null)
            {
                return NotFound();
            }
            ViewData["CategorieID"] = new SelectList(_context.Categorie, "CategorieID", "CategorieID", Project.CategorieID);
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", Project.UserID);
            return View(Project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Moderator")]
        public async Task<IActionResult> Edit(int id, [Bind("ProjectID,UserID,Titel,Omschrijving,CategorieID,Datum,Foto,Gesloten")] Project ervaring)
        {
            if (id != ervaring.MeldingID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ervaring);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(ervaring.MeldingID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategorieID"] = new SelectList(_context.Categorie, "CategorieID", "CategorieID", ervaring.CategorieID);
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", ervaring.UserID);
            return View(ervaring);
        }

        // GET: Projects/Delete/5
        [Authorize(Roles = "Moderator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Project = await _context.Projects
                .Include(m => m.Categorie)
                .Include(m => m.User)
                .FirstOrDefaultAsync(m => m.MeldingID == id);
            if (Project == null)
            {
                return NotFound();
            }

            return View(Project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Moderator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Project = await _context.Projects.FindAsync(id);
            _context.Projects.Remove(Project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(OverzichtProjecten));
        }

        private bool ProjectExists(int id)
        {
            return _context.Projects.Any(e => e.MeldingID == id);
        }

        //Indexpagina die wordt gebruikt om Projecten weer te geven, opgedeeld in pagina's
        public async Task<IActionResult> OverzichtProjecten(int pagina, string sorteerType, string sorteerVolgorde, string filter, string status, string poster, DateTime date1, DateTime date2, bool likedby)
        {
            //var ip = _accessor.ActionContext.HttpContext.Connection.RemoteIpAddress.ToString();
            //Console.WriteLine(ip);

Views/Shared/_IngelogdPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Portfolio_Site.Areas.Identity.Data

@inject SignInManager<_Portfolio_Site_User> SignInManager
@inject UserManager<_Portfolio_Site_User> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <ul class="navbar-nav flex-grow-1 navabar-left">
        <li class="nav-item tooltip2">
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="OverMij">Over mij</a>
            <span id="rondleiding1" class="tooltiptext">
                <b>Over mij:</b> Via de over mij pagina kunt u informatie vinden over wie ik ben en wat ik doe.
                <br>
                <button class="btn btn-primary" onclick="rondleidingVolgende('rondleiding1', 'rondleiding2')">Volgende</button>
            </span>
        </li>
        <li class="nav-item tooltip2">
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
            <span id="rondleiding2" class="tooltiptext">
                <b>Contact:</b> Via de Contact pagina kunt u mijn contact gegevens vinden.
                <br>
                <button class="btn btn-primary" onclick="rondleidingVolgende('rondleiding2', 'rondleiding3')">Volgende</button>
            </span>
        </li>

        <li class="nav-item tooltip2">
            <a class="nav-link" asp-area="" asp-controller="Project" asp-action="OverzichtProjecten">Ervaring</a>
            <span id="rondleiding3" class="tooltiptext">
                <b>Ervaring:</b> Hier kunt u mijn ervaring tot nu toe zien. Denk hierbiij aan werk ervaring of school projecten.
                <br>
                <button class="btn btn-primary" onclick="rondleidingVolgende('rondleiding3', 'rondleiding4')">Volgende</button>
            </span>
        </li>
        <li class="nav-item tooltip2">
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Helpdesk">Helpdesk</a>
            <span id="rondleiding4" class="tooltiptext">
                <b>Helpdesk:</b> Op de helpdesk kunt u de meest gestelde vragen bekijken en staat onze email voor als u ons wilt contacteren.
                <br>
                <button class="btn btn-primary" onclick="rondleidingVolgende('rondleiding4', 'rondleiding5')">Volgende</button>
            </span>
        </li>
        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Moderator"))
        {
            <li class="nav-item dropdown tooltip2">
                <a style="color:red" class="nav-link dropdown-toggle" asp-area="" data-toggle="dropdown">Moderator</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" asp-area="" asp-controller="Port_Eigenaar" asp-action="Index">Portfolio Eigenaar</a></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Programeertaal" asp-action="Index">Programeer talen</a></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Hobby" asp-action="Index">Hobby's</a></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="MiddelbareSchool" asp-action="Index">Middelbare school</a></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="HogereSchool" asp-action="Index">Hogere school</a></li>
                    
                    <li class="dropdown-divider"></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                    
                    <li class="dropdown-divider"></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Project" asp-action="Create">Nieuwe ervaring toevoegen</a></li>
                </ul>
            </li>
        }
    </ul>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/home.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
</head>
<body>
    <header>
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <div class="tooltip2">
                    <a class="navbar-brand" style="font-size:medium" asp-area="" asp-controller="Home" asp-action="Index">Portfolio</a>
                    <span id="rondleiding0" class="tooltiptext">
                        <b>Homepage:</b>Op de homepagina kunt u informatie over het Portfolio lezen.
                        <br>
                        <button class="btn btn-primary" onclick="rondleidingVolgende('rondleiding0', 'rondleiding1')">Volgende</button>
                    </span>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <partial name="_IngelogdPartial">
                        <partial name="_LoginPartial">
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="footer-basic">
        <footer>
            <p style="text-align: center;"> &copy; 2022 - Portfolio - <a asp-area="" asp-controller="Home" asp-action="Privacy" style="color:blue;">Privacy</a></p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_ModeratorPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Portfolio_Site.Areas.Identity.Data

@inject SignInManager<_Portfolio_Site_User> SignInManager
@inject UserManager<_Portfolio_Site_User> UserManager

<ul class="navbar-nav text-color">

</ul>