Models/Port_Eigenaar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;

namespace Portfolio_Site.Models
{
    public class Port_Eigenaar
    {
        [Key]
        public int Id { get; set; }
        public string Naam { get; set; }
        public int Leeftijd { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Geboortedatum { get; set; }

        public string Nationaliteit { get; set; }

        //contact info
        public string Adres { get; set; }
        public string PostCode { get; set; }
        public string Plaats { get; set; }
        public string LinkedIn { get; set; }

        public string BeschrijvingProgrammeer { get; set; }

        [Required(ErrorMessage = "Please choose profile picture")]  
        public string ProfilePicture { get; set; }  

        public int Telefoon { get; set; }
        public string Email { get; set; }

    }

    public class Hobby {
        [Key]
        public int Id { get; set; }

        public Port_Eigenaar port_Eigenaar { get; set; }

        public string Naam { get; set; }
    }

    public class Programeertaal
    {
        [Key]
        public int Id { get; set; }

        public Port_Eigenaar port_Eigenaar { get; set; }
        
        public string Naam { get; set; }
        public int Kennis { get; set; }
    }

    public class MiddelbareSchool
    {
        [Key]
        public int Id { get; set; }

        public Port_Eigenaar port_Eigenaar { get; set; }
        
        public string Naam { get; set; }
        public string Opleiding { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Begin_Datum { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Eind_Datum { get; set; }
    }

    public class HogereSchool
    {
        [Key]
        public int Id { get; set; }

        public Port_Eigenaar port_Eigenaar { get; set; }
        
        public string Naam { get; set; }
        public string Opleiding { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Begin_Datum { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Eind_Datum { get; set; }
    }
}

Controllers/HobbyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Portfolio_Site.Data;
using Portfolio_Site.Models;

namespace Portfolio_Site.Controllers
{
    public class HobbyController : Controller
    {
        private readonly _Portfolio_Site_Dbcontext _context;

        public HobbyController(_Portfolio_Site_Dbcontext context)
        {
            _context = context;
        }

        // GET: Hobby
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hobbys.ToListAsync());
        }

        // GET: Hobby/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hobby = await _context.Hobbys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hobby == null)
            {
                return NotFound();
            }

            return View(hobby);
        }

        // GET: Hobby/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Hobby/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("Naam")] Hobby hobby)
        {
            if (ModelState.IsValid)
            {
                Port_Eigenaar eigenaar = await _context.Port_Eigenaar.FindAsync(id);
                hobby.port_Eigenaar = eigenaar;
                _context.Add(hobby);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hobby);
        }

        // GET: Hobby/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hobby = await _context.Hobbys.FindAsync(id);
            if (hobby == null)
            {
                return NotFound();
            }
            return View(hobby);
        }

        // POST: Hobby/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naam")] Hobby hobby)
        {
            if (id != hobby.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hobby);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HobbyExists(hobby.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hobby);
        }

        // GET: Hobby/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hobby = await _context.Hobbys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hobby == null)
            {
                return NotFound();
            }

            return View(hobby);
        }

        // POST: Hobby/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hobby = await _context.Hobbys.FindAsync(id);
            _context.Hobbys.Remove(hobby);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HobbyExists(int id)
        {
            return _context.Hobbys.Any(e => e.Id == id);
        }
    }
}

Controllers/HogereSchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Portfolio_Site.Data;
using Portfolio_Site.Models;

namespace Portfolio_Site.Controllers
{
    public class HogereSchoolController : Controller
    {
        private readonly _Portfolio_Site_Dbcontext _context;

        public HogereSchoolController(_Portfolio_Site_Dbcontext context)
        {
            _context = context;
        }

        // GET: HogereSchool
        public async Task<IActionResult> Index()
        {
            return View(await _context.HogereSchools.ToListAsync());
        }

        // GET: HogereSchool/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hogereSchool = await _context.HogereSchools
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hogereSchool == null)
            {
                return NotFound();
            }

            return View(hogereSchool);
        }

        // GET: HogereSchool/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: HogereSchool/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("Naam,Opleiding,Begin_Datum,Eind_Datum")] HogereSchool hogereSchool)
        {
            if (ModelState.IsValid)
            {
                Port_Eigenaar eigenaar = await _context.Port_Eigenaar.FindAsync(id);
                hogereSchool.port_Eigenaar = eigenaar;
                _context.Add(hogereSchool);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hogereSchool);
        }

        // GET: HogereSchool/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hogereSchool = await _context.HogereSchools.FindAsync(id);
            if (hogereSchool == null)
            {
                return NotFound();
            }
            return View(hogereSchool);
        }

        // POST: HogereSchool/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naam,Opleiding,Begin_Datum,Eind_Datum")] HogereSchool hogereSchool)
        {
            if (id != hogereSchool.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hogereSchool);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HogereSchoolExists(hogereSchool.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hogereSchool);
        }

        // GET: HogereSchool/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hogereSchool = await _context.HogereSchools
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hogereSchool == null)
            {
                return NotFound();
            }

            return View(hogereSchool);
        }

        // POST: HogereSchool/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hogereSchool = await _context.HogereSchools.FindAsync(id);
            _context.HogereSchools.Remove(hogereSchool);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HogereSchoolExists(int id)
        {
            return _context.HogereSchools.Any(e => e.Id == id);
        }
    }
}

Controllers/ProgrameertaalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Portfolio_Site.Data;
using Portfolio_Site.Models;

namespace Portfolio_Site.Controllers
{
    public class ProgrameertaalController : Controller
    {
        private readonly _Portfolio_Site_Dbcontext _context;

        public ProgrameertaalController(_Portfolio_Site_Dbcontext context)
        {
            _context = context;
        }

        // GET: Programeertaal
        public async Task<IActionResult> Index()
        {
            return View(await _context.Programeertaal.ToListAsync());
        }

        // GET: Programeertaal/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var programeertaal = await _context.Programeertaal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (programeertaal == null)
            {
                return NotFound();
            }

            return View(programeertaal);
        }

        // GET: Programeertaal/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Programeertaal/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("Naam,Kennis")] Programeertaal programeertaal)
        {
            //programeertaal.port_Eigenaar = eigenaar;
            if (ModelState.IsValid)
            {
                Port_Eigenaar eigenaar = await _context.Port_Eigenaar.FindAsync(id);
                programeertaal.port_Eigenaar = eigenaar;
                _context.Add(programeertaal);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(programeertaal);
        }

        // GET: Programeertaal/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var programeertaal = await _context.Programeertaal.FindAsync(id);
            if (programeertaal == null)
            {
                return NotFound();
            }
            return View(programeertaal);
        }

        // POST: Programeertaal/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naam,Kennis")] Programeertaal programeertaal)
        {
            if (id != programeertaal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(programeertaal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProgrameertaalExists(programeertaal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(programeertaal);
        }

        // GET: Programeertaal/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var programeertaal = await _context.Programeertaal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (programeertaal == null)
            {
                return NotFound();
            }

            return View(programeertaal);
        }

        // POST: Programeertaal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var programeertaal = await _context.Programeertaal.FindAsync(id);
            _context.Programeertaal.Remove(programeertaal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProgrameertaalExists(int id)
        {
            return _context.Programeertaal.Any(e => e.Id == id);
        }
    }
}

Views/Port_Eigenaar/Create.cshtml
@model Portfolio_Site.ViewModels.Port_EigenaarViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Port_Eigenaar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">  
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Leeftijd" class="control-label"></label>
                <input asp-for="Leeftijd" class="form-control" />
                <span asp-validation-for="Leeftijd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Geboortedatum" class="control-label"></label>
                <input asp-for="Geboortedatum" class="form-control" />
                <span asp-validation-for="Geboortedatum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationaliteit" class="control-label"></label>
                <input asp-for="Nationaliteit" class="form-control" />
                <span asp-validation-for="Nationaliteit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adres" class="control-label"></label>
                <input asp-for="Adres" class="form-control" />
                <span asp-validation-for="Adres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostCode" class="control-label"></label>
                <input asp-for="PostCode" class="form-control" />
                <span asp-validation-for="PostCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plaats" class="control-label"></label>
                <input asp-for="Plaats" class="form-control" />
                <span asp-validation-for="Plaats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedIn" class="control-label"></label>
                <input asp-for="LinkedIn" class="form-control" />
                <span asp-validation-for="LinkedIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div> 
            <div class="form-group">
                <label asp-for="Telefoon" class="control-label"></label>
                <input asp-for="Telefoon" class="form-control" />
                <span asp-validation-for="Telefoon" class="text-danger"></span>
            </div> 
            <div class="form-group">
                <label asp-for="BeschrijvingProgrammeer" class="control-label"></label>
                <input asp-for="BeschrijvingProgrammeer" class="form-control" />
                <span asp-validation-for="BeschrijvingProgrammeer" class="text-danger"></span>
            </div>

            @* Form voor image *@
            <div class="form-group">  
                <label asp-for="ProfileImage" class="control-label"></label>  
                <div class="custom-file">  
                    <input asp-for="ProfileImage" class="custom-file-input" id="customFile" accept="image/*">  
                    <label class="custom-file-label" for="customFile">Choose file</label>  
                </div>  
                <span asp-validation-for="ProfileImage" class="text-danger"></span>  
            </div>  
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">  
        // Add the following code if you want the name of the file appear on select  
        $(".custom-file-input").on("change", function () {  
            var fileName = $(this).val().split("\\").pop();  
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);  
        });  
    </script>  
}  

Views/Port_Eigenaar/Delete.cshtml
@model Portfolio_Site.Models.Port_Eigenaar

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Port_Eigenaar</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Leeftijd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Leeftijd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Geboortedatum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Geboortedatum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nationaliteit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nationaliteit)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plaats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plaats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkedIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkedIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefoon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefoon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BeschrijvingProgrammeer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BeschrijvingProgrammeer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Port_Eigenaar/Details.cshtml
@model Portfolio_Site.Models.Port_Eigenaar

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Port_Eigenaar</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Leeftijd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Leeftijd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Geboortedatum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Geboortedatum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nationaliteit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nationaliteit)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plaats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plaats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkedIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkedIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefoon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefoon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BeschrijvingProgrammeer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BeschrijvingProgrammeer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Port_Eigenaar/Index.cshtml
@model IEnumerable<Portfolio_Site.Models.Port_Eigenaar>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Leeftijd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Geboortedatum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nationaliteit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adres)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Plaats)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LinkedIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefoon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BeschrijvingProgrammeer)
            </th>

            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>  
                <img src="~/images/@item.ProfilePicture" class="rounded-circle" height="40" width="40" asp-append-version="true" /> 
                @Html.DisplayFor(modelItem => item.Naam)
            </td>  
            <td>
                @Html.DisplayFor(modelItem => item.Leeftijd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Geboortedatum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nationaliteit)
            </td>            
            <td>
                @Html.DisplayFor(modelItem => item.Adres)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Plaats)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LinkedIn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefoon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BeschrijvingProgrammeer)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
            <td>
                <a asp-controller="Programeertaal" asp-action="Create" asp-route-id="@item.Id">Programeertalen</a> <br>
                <a asp-controller="Hobby" asp-action="Create" asp-route-id="@item.Id">Hobby's</a> <br>
                <a asp-controller="MiddelbareSchool" asp-action="Create" asp-route-id="@item.Id">Middelbare School</a> <br>
                <a asp-controller="HogereSchool" asp-action="Create" asp-route-id="@item.Id">Hogere School</a>
            </td>
        </tr>
}
    </tbody>
</table>